name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  compile-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependecies
        run: npm ci
      - name: Compile
        run: npm run build
      - name: Test
        run: npm test
  run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependecies
        run: npm ci
      - name: Run
        run: npx ts-node ./test/test.ts "$SERVICE_ID" 5
        env:
          SERVICE_ID: ${{ secrets.SERVICE_ID }} 5
